title: StandardX
description: A compilation of US teaching standards for English, math, science, and social studies, and the code used to generate it. Why? To make it easier to develop interdisciplinary lessons.
show_downloads: true
theme: jekyll-theme-architect
